name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK 8
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 8

      - name: Import GPG Owner Trust
        run: echo ${{secrets.GPG_OWNERTRUST}} | base64 --decode | gpg --import-ownertrust

      - name: Import GPG key
        run: echo ${{secrets.GPG_SECRET_KEYS}} | base64 --decode | gpg --import --no-tty --batch --yes

      - name: Clean settings.xml
        run: rm -rf ~/.m2/settings.xml

      - name: Create settings.xml
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: '[{"id": "central", "username": "${{secrets.CENTRAL_USERNAME}}", "password": "${{secrets.CENTRAL_PASSWORD}}"}]'

      - name: Build and deploy to Maven Central
        run: mvn --batch-mode --update-snapshots clean deploy -Prelease -Dgpg.keyname=${{secrets.GPG_KEYNAME}} -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}
